In [8]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
a = np.array([[1,  2],  [3,  4]])
a

array([[1, 2],
       [3, 4]])

In [14]:
a[0][0],a[1][1]

(1, 4)

In [18]:
a = np.array([1, 2, 3, 4, 5], ndmin =  2)

In [20]:
print(a)

[[1 2 3 4 5]]


In [24]:
a = np.arange(24)
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print (b.ndim)
a,b

1
3


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]]))

In [26]:
a = np.array([[1,2,3],[4,5,6]])
print (a.shape)

(2, 3)


In [27]:
import numpy as np

x = np.array([[1,  2],  [3,  4],  [5,  6]])
y = x[[0,1,2],  [0,1,0]]
print (y)

[1 4 5]


### numpy的计算

In [30]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

[ 10  40  90 160]


### 广播机制

In [32]:
import numpy as np
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([0,1,2])
print(a + b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [35]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
bb = np.tile(b, (4,1))  # 重复 b 的各个维度 将数组 b 在行维度上重复4次，在列维度上重复1次。
a,bb

(array([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30]]),
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]))

In [39]:
a = np.array([0,3.14159/2,45,60,90])
print ('不同角度的正弦值：')
# 通过乘 pi/180 转化为弧度
np.sin(a)

不同角度的正弦值：


array([ 0.        ,  1.        ,  0.85090352, -0.30481062,  0.89399666])

In [41]:
a = np.array([0.25,  1.33,  1,  100])
print ('我们的数组是：')
print (a)
print ('\n')
print ('调用 reciprocal 函数：')
print (np.reciprocal(a))

我们的数组是：
[  0.25   1.33   1.   100.  ]


调用 reciprocal 函数：
[4.        0.7518797 1.        0.01     ]


In [43]:
a = np.array([2,3,6])
print ('我们的数组是；')
print (a)
print ('\n')
print ('调用 power 函数：')
print (np.power(a,2))
print ('\n')
print ('第二个数组：')
b = np.array([1,2,3])
print (b)
print ('\n')
print ('再次调用 power 函数：')
print (np.power(a,b))

我们的数组是；
[2 3 6]


调用 power 函数：
[ 4  9 36]


第二个数组：
[1 2 3]


再次调用 power 函数：
[  2   9 216]
