In [1]:
import torch
from torch import nn

net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(2, 4)
X

tensor([[0.5022, 0.9179, 0.9019, 0.5201],
        [0.0594, 0.0461, 0.4451, 0.2992]])

In [2]:
net(X)

tensor([[-0.0587],
        [ 0.0592]], grad_fn=<AddmmBackward0>)

In [3]:
net

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [11]:
import torch
import torch.nn as nn

# 定义一个简单的线性层
class LinearLayer(nn.Module):
    def __init__(self, in_features, out_features):
        super(LinearLayer, self).__init__()
        self.linear = nn.Linear(in_features, out_features)

    def forward(self, x):
        return self.linear(x)


# 创建线性层实例
linear_layer = LinearLayer(3, 2)
# 输入数据
input_data = torch.tensor([1.0, 2.0, 3.0])
# 前向传播
output = linear_layer(input_data)
input_data, output

(tensor([1., 2., 3.]), tensor([1.2173, 0.7999], grad_fn=<ViewBackward0>))

In [17]:
# 获取权重参数
weights = linear_layer.linear.weight.data
print(weights.shape)

torch.Size([2, 3])


In [18]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)  # torch.Size([2, 3])

x_flatten = x.flatten()
print(x_flatten.shape)  # torch.Size([6])
print(x_flatten)  # tensor([1, 2, 3, 4, 5, 6])

torch.Size([2, 3])
torch.Size([6])
tensor([1, 2, 3, 4, 5, 6])


In [19]:
import torch
from torch import nn
from d2l import torch as d2l

net = nn.Sequential(
    nn.Conv2d(1, 6, kernel_size=5, padding=2), nn.Sigmoid(),
    nn.AvgPool2d(kernel_size=2, stride=2),
    nn.Conv2d(6, 16, kernel_size=5), nn.Sigmoid(),
    nn.AvgPool2d(kernel_size=2, stride=2),
    nn.Flatten(),
    nn.Linear(16 * 5 * 5, 120), nn.Sigmoid(),
    nn.Linear(120, 84), nn.Sigmoid(),
    nn.Linear(84, 10))

In [20]:
net

Sequential(
  (0): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (1): Sigmoid()
  (2): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (3): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (4): Sigmoid()
  (5): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (6): Flatten(start_dim=1, end_dim=-1)
  (7): Linear(in_features=400, out_features=120, bias=True)
  (8): Sigmoid()
  (9): Linear(in_features=120, out_features=84, bias=True)
  (10): Sigmoid()
  (11): Linear(in_features=84, out_features=10, bias=True)
)

In [21]:
X = torch.rand(size=(1, 1, 28, 28), dtype=torch.float32)
for layer in net:
    X = layer(X)
    print(layer.__class__.__name__, 'output shape: \t', X.shape)

Conv2d output shape: 	 torch.Size([1, 6, 28, 28])
Sigmoid output shape: 	 torch.Size([1, 6, 28, 28])
AvgPool2d output shape: 	 torch.Size([1, 6, 14, 14])
Conv2d output shape: 	 torch.Size([1, 16, 10, 10])
Sigmoid output shape: 	 torch.Size([1, 16, 10, 10])
AvgPool2d output shape: 	 torch.Size([1, 16, 5, 5])
Flatten output shape: 	 torch.Size([1, 400])
Linear output shape: 	 torch.Size([1, 120])
Sigmoid output shape: 	 torch.Size([1, 120])
Linear output shape: 	 torch.Size([1, 84])
Sigmoid output shape: 	 torch.Size([1, 84])
Linear output shape: 	 torch.Size([1, 10])


In [8]:
# With Learnable Parameters‘
import torch
from torch import nn

m = nn.BatchNorm2d(1)
# Without Learnable Parameters
m = nn.BatchNorm2d(1, affine=False)
input = torch.tensor([[10, 20, 30],
                      [5, 10, 15],
                      [15, 25, 35],
                      [20, 30, 40]],dtype=torch.float32)
input=torch.reshape(input,(1,1,4,3))

output = m(input)
output

tensor([[[[-1.0783, -0.1198,  0.8387],
          [-1.5575, -1.0783, -0.5990],
          [-0.5990,  0.3594,  1.3179],
          [-0.1198,  0.8387,  1.7971]]]])

In [10]:
# With Learnable Parameters
m = nn.BatchNorm2d(100)
# Without Learnable Parameters
m = nn.BatchNorm2d(100, affine=False)
input = torch.randn(20, 100, 35, 45)
output = m(input)
output

tensor([[[[ 2.6192e-01,  6.4690e-02, -7.6080e-01,  ..., -1.4802e+00,
            1.6848e+00,  8.8658e-01],
          [-3.8446e-01, -9.5117e-04,  1.9758e+00,  ...,  9.1725e-01,
            6.4250e-01, -9.1413e-01],
          [-1.3996e+00,  1.2922e+00, -2.6763e-01,  ...,  1.4828e+00,
            8.6064e-01,  1.0947e+00],
          ...,
          [ 1.0388e+00,  1.0541e+00, -1.3746e+00,  ...,  5.5614e-03,
            1.0735e+00,  5.7630e-01],
          [-3.6401e-01, -1.0425e+00,  7.3467e-01,  ..., -6.9850e-02,
           -1.5262e+00, -5.4492e-01],
          [-1.3980e+00, -8.7290e-01, -1.2957e-01,  ...,  3.7508e-01,
           -8.7559e-01,  4.5072e-02]],

         [[ 1.2523e+00,  2.4194e+00, -6.8633e-01,  ...,  6.6588e-01,
            4.3631e-01,  1.9580e-01],
          [-9.4195e-02, -1.8806e+00, -1.7267e+00,  ...,  4.7139e-02,
           -7.2491e-01, -2.7867e-01],
          [ 1.3062e+00, -9.9480e-01, -5.9085e-01,  ...,  1.3252e+00,
            1.2739e+00,  1.5733e+00],
          ...,
     