In [6]:
import torch
from torch import nn
from torch.nn import functional as F
net = nn.Sequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))
X = torch.rand(1, 20)
net(X)

tensor([[-0.2454, -0.6659,  0.1621, -0.0550, -0.0645,  0.1295, -0.1575,  0.1042,
         -0.0605,  0.0157]], grad_fn=<AddmmBackward0>)

In [7]:
X,net

(tensor([[0.3830, 0.6328, 0.9554, 0.8925, 0.4519, 0.9762, 0.6560, 0.3804, 0.5863,
          0.5035, 0.5963, 0.8555, 0.3673, 0.8828, 0.9077, 0.9555, 0.9473, 0.9017,
          0.5130, 0.1216]]),
 Sequential(
   (0): Linear(in_features=20, out_features=256, bias=True)
   (1): ReLU()
   (2): Linear(in_features=256, out_features=10, bias=True)
 ))

In [8]:
class MLP(nn.Module):
    # 用模型参数声明层。这里，我们声明两个全连接的层
    def __init__(self):
        # 调用MLP的父类Module的构造函数来执行必要的初始化。
        # 这样，在类实例化时也可以指定其他函数参数，例如模型参数params（稍后将介绍）
        super().__init__()
        self.hidden = nn.Linear(20, 256)  # 隐藏层
        self.out = nn.Linear(256, 10)  # 输出层

    # 定义模型的前向传播，即如何根据输入X返回所需的模型输出
    def forward(self, X):
        # 注意，这里我们使用ReLU的函数版本，其在nn.functional模块中定义。
        return self.out(F.relu(self.hidden(X)))

In [9]:
net = MLP()
net(X)

tensor([[-0.2480,  0.0676,  0.0338, -0.2289, -0.0684, -0.3849,  0.1952, -0.1160,
         -0.1524, -0.0292]], grad_fn=<AddmmBackward0>)